### ISSUE TITLE
FEATURE - ADD KIND INFRA TO KIND PLAY

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/ansible#178]
```yaml
---
helmDefaults:
  verify: false
  wait: true
  timeout: 600
  recreatePods: false
  force: true

helmfiles:
  - path: /home/sthings/projects/helm/infra/cilium.yaml
    values:
      - version: 1.17.1
      - config: kind
      - ipRangeStart: 172.18.250.0
      - ipRangeEnd: 172.18.250.50
      - clusterName: helm-dev

  - path: /home/sthings/projects/helm/infra/ingress-nginx.yaml
    values:
      - enableHostPort: true
      - version: 4.12.0

  - path: /home/sthings/projects/helm/infra/cert-manager.yaml
    values:
      - version: v1.17.1
      - config: selfsigned
```
